#!/bin/bash
set -o errexit -o nounset -o pipefail

source .env

function write_config_options(){
    echo "write config options to $1"
    eval "echo \"$(cat $1)\"" > $1
}

function livy_server_service(){
    echo "starting Livy Server!"
    /opt/livy/bin/livy-server start

    # whatever blocking call
    tail -f /dev/null
}

function main(){
  case "$1" in
    livy)
      write_config_options /opt/livy/conf/livy.conf
      write_config_options /opt/hadoop/etc/hadoop/core-site.xml
      livy_server_service
      start
      echo "done. now waiting for services."
      ;;
    *)
      exec "$@"
      ;;
  esac
}

main $1

