name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        spark:
          - 2.4.5
          - 2.4.4
          - 2.4.3
          - 2.4.2
          - 2.4.1
          - 2.4.0
          - 2.3.2
          - 2.3.1
          - 2.3.0
          - 2.2.2
          - 2.2.1
          - 2.2.0
          - 2.1.3
          - 2.1.2
          - 2.1.1
          - 2.1.0
          - 2.0.2
          - 2.0.1
          - 2.0.0
          - 2.0.0
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Image and run tests
        uses: docker/build-push-action@v2
        with:
          build-args: |
            SPARK_VERSION=${{ matrix.spark }}

