name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        spark:
          - 3.2.0
          - 3.1.2
          - 3.1.1
          - 3.0.1
          - 3.0.0
          - 2.4.8
          - 2.4.7
          - 2.4.6
          - 2.4.5
          - 2.4.4
          - 2.4.3
          - 2.4.2
          - 2.4.1
          - 2.4.0
          - 2.3.2
          - 2.3.1
          - 2.3.0
          - 2.2.2
          - 2.2.1
          - 2.2.0
          - 2.1.3
          - 2.1.2
          - 2.1.1
          - 2.1.0
          - 2.0.2
          - 2.0.1
          - 2.0.0
          - 2.0.0
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          build_args: SPARK_VERSION=${{ matrix.spark }}
          tags: 0.5.0-spark${{ matrix.spark }}
