name: Docker Image CI

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*.*.*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        spark:
          - 2.4.5
          - 2.4.4
          - 2.4.3
          - 2.4.2
          - 2.4.1
          - 2.4.0
          - 2.3.2
          - 2.3.1
          - 2.3.0
          - 2.2.2
          - 2.2.1
          - 2.2.0
          - 2.1.3
          - 2.1.2
          - 2.1.1
          - 2.1.0
          - 2.0.2
          - 2.0.1
          - 2.0.0
          - 2.0.0
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Get Release Tag
        id: gettag
        run: echo "::set-output name=tag::$(echo ${GITHUB_REF:10})"
      - name: Build the Docker image
        run: docker build -t davlum/localemr-container:ci --build-arg SPARK_VERSION=${{ matrix.spark }} .
      - name: Run the server
        run: docker run -d --name localemr-container davlum/localemr-container:ci
      - name: Run tests
        run: docker exec localemr-container pipenv run pytest
      - name: Push to Dockerhub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: davlum/localemr-container
          build_args: SPARK_VERSION=${{ matrix.spark }}
          tags: ${{ steps.gettag.outputs.tag }}-spark${{ matrix.spark }},latest-spark${{ matrix.spark }}
          target: app

